# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6254976317310db9225b0520cad0e090a4e66de7fdece5b383e8a0bc19a3567214e61e173dae6ec2d0831bd2abcdadd1f9b766862996e10ada925b7cf92b3b4

test:
  secret_key_base: 54773dceaf1ada0e276c9d3e6992ea071d2a4fcf750b5d6db571f03a628f7ae6e066b6d0ed30a6f71ac8cb13d117ed0f747a8a28ca8c87bcee0b663920704014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
